##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile
##

NAME	=	libasm.so

all:	$(NAME)

$(NAME):
	ghc wolfram.hs

clean:
		rm -f wolfram.hi
		rm -f wolfram.o

fclean: clean
		rm -f wolfram

re: fclean all
